logging:
  level:
    root: info
  file:
    path: /var/log/own-open-apis

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: active
        readiness:
          include: ready

own:
  open-apis:
    storage:
      memory:
        max-rows: 10