app:
  replicaCount: 1
  resources:
      cpu: "2"
      memory: "256Mi"
  port: 18081
  image:
    repository: "striveonger/own-open-apis"
    tag: "1.0.0"
    pullPolicy: "IfNotPresent"
  ingress:
    enabled: true
    path: "/own/open/api"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
