---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ include "own-open-apis.name" . }}-deployment"
  labels:
{{ include "own-open-apis.labels" .  | indent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
{{ include "own-open-apis.selectorLabels" .  | indent 6 }}
  template:
    metadata:
      namespace: "{{ .Release.Namespace }}"
      name: "{{ include "own-open-apis.name" . }}"
      labels:
{{ include "own-open-apis.labels" .  | indent 8 }}
    spec:
      containers:
        - name: "{{ include "own-open-apis.name" . }}"
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: "{{.Values.app.image.pullPolicy }}"
          resources:
            limits:
              cpu: "{{ .Values.app.resources.cpu }}"
              memory: "{{ .Values.app.resources.memory }}"
            requests:
              cpu: "{{ .Values.app.resources.cpu }}"
              memory: "{{ .Values.app.resources.memory }}"
          ports:
            - containerPort: {{ .Values.app.port }}
              protocol: "TCP"
          volumeMounts:
          - name: node-logs
            mountPath: /var/log/own-open-apis
          env:
{{- toYaml .Values.env | nindent 10 }}
      restartPolicy: "Always"
      volumes:
      - name: node-logs
        hostPath:
          path: /var/log/own-open-apis
          type: "DirectoryOrCreate"