{{- if .Values.app.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "own-open-apis.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "own-open-apis.labels" .  | indent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.app.ingress.path }}`)
      kind: Rule
      services:
        - name: {{ include "own-open-apis.name" . }}-service
          port: {{ .Values.app.port  }}
{{- end -}}