app:
  port: 18081
  replicaCount: 1
  image:
    repository: "striveonger/own-open-apis"
    tag: "1.0.0"
    pullPolicy: "IfNotPresent"
  probe:
    enabled: true
  resources:
    cpu: "2"
    memory: "256Mi"
  log:
    path: "/var/log/"
  ingress:
    enabled: true
    path: "/own/open"
  config:
    applicationYaml:
      logging:
        level:
          root: info
      own:
        open-apis:
          storage:
            memory:
              max-rows: 10

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"